import react, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import api from '../api/adapter/'

export default function Home() {
  const [data, setData] = react.useState(null)

  const fetchData = async () => {
    try {
      const dataResponse = await api.post('/', {
        product: 'Berserk Edição de Luxo',
        quantity: 10
      }, {
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
          'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization',
          'Access-Control-Allow-Credentials': true,

        }
      })
      setData(dataResponse.data)
    } catch (error) {
      console.error("FALHA NA REQUISIÇÃO", error)
    }
  }

  useEffect(() => {
    console.log('Home page rendered')
    fetchData()
  }, [])

  useEffect(() => {
    console.log('data Response ->', data)
  }, [data])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <table>
          <tr>
            <th>ID</th>
            <th>Imagem</th>
            <th>Produto</th>
            <th>Preço</th>
            <th>Classificação</th>
            <th>Link</th>
          </tr>
          {data && data.data && data.data.map((item, index) => {
            return (
              <tr key={index}>
                <td>{item.productID}</td>
                <td><img src={item.image} /></td>
                <td><h1>{item.name}</h1></td>
                <td><h2>R$ {item.price.toFixed(2)}</h2></td>
                <td><h2>{item.stars}</h2></td>
                <td><a href={item.link}>Link</a></td>
              </tr>
            )
          })}
          </table>
        

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
